version: "3.5"

services:
  server:
    build:
      context: .
      args:
        PYTHON_ENV: development
    command: python -m app.server
    restart: always
    environment:
      PYTHON_ENV: development
      APP_PORT: 8000
      APP_HOST: 0.0.0.0
    volumes:
      - "./app/:/usr/src/app/app/"
    container_name: flask-server
    ports:
      - 9876:8000
